### ISSUE TITLE
Add option to start server with required parameters

### ISSUE THREAD

**Issue by leonadler** [cprerovsky/moonar-lander#18]
Could be done via cli:
```
$ node moonar-lander/index.js --max-clients 2 --seed MYSEED
ws://localhost:4711
```
or (better?) via JavaScript
```JavaScript
server = require('../moonar-lander/server');
server.start({ seed: 'MYSEED', maxClients: 2 })
    .then(webSocketAddress => {
        // connect client
    });
```

This would need the physics engine to run on the server (it runs in the host browser now iirc).

**Comment by cprerovsky** [comment]
Did not exactly implement that but now you can connect at any time to the server and then do a ```GET http://localhost:4711/game/:seed``` and you're golden. Won't do anything beyond that atm.
