### ISSUE TITLE
Occasional server crash

### ISSUE THREAD

**Issue by michaelbromley** [cprerovsky/moonar-lander#20]
I am getting occasional crashes of the backend with the following error in the console:

```
[supervisor] E:\GitHub\moonar-lander\backend\build\index.js:37
[supervisor]                 clientSocket(wss, hc.val).send(hc.data);
[supervisor]                                          ^
[supervisor]
[supervisor] TypeError: Cannot read property 'send' of undefined
[supervisor]     at message (E:\GitHub\moonar-lander\backend\build\index.js:37:42)
[supervisor]     at WebSocket.ws.on (E:\GitHub\moonar-lander\backend\build\index.js:28:32)
[supervisor]     at emitTwo (events.js:106:13)
[supervisor]     at WebSocket.emit (events.js:191:7)
[supervisor]     at Receiver.ontext (E:\GitHub\moonar-lander\node_modules\ws\lib\WebSocket.js:841:10)
[supervisor]     at E:\GitHub\moonar-lander\node_modules\ws\lib\Receiver.js:536:18
[supervisor]     at E:\GitHub\moonar-lander\node_modules\ws\lib\Receiver.js:368:7
[supervisor]     at E:\GitHub\moonar-lander\node_modules\ws\lib\PerMessageDeflate.js:249:5
[supervisor]     at afterWrite (_stream_writable.js:361:3)
[supervisor]     at onwrite (_stream_writable.js:352:7)
[supervisor] [nodemon] app crashed - waiting for file changes before starting...
```

Not sure what the exact sequence is which causes this. Seems kinda random so far.

**Comment by michaelbromley** [comment]
Figured out the sequence to reproduce:

1. Connect a client and start the game.
2. Let the client die so the "game over" screen shows.
3. Kill the websocket connection, e.g. by refreshing the browser.
4. Should see the crash above.

**Comment by cprerovsky** [comment]
Thanks for the steps to reproduce! Will refactor the whole architecture over the weekend (I hope) to run the game on the server-side, with the web ui just being a "viewer" for the game. I will also rework connection handling there and make it more resilient.

**Comment by cprerovsky** [comment]
Just finished refactoring the whole thing. The crash shown above can absolutely not happen again as I changed everything. I am very confident that I introduced new bugs - the server WILL crash, I promise.
